### ISSUE TITLE
Perceval gitee with repository parameter？

### ISSUE THREAD

**Issue by bluejeams** [grimoirelab-gitee/grimoirelab-perceval-gitee#10]
When execute perceval gitee https://gitee.com/willemjiang/gitee-example，receive an error message :perceval: error: the following arguments are required: repository. It seems miss the repository parameter,. so i add the repository within the command line. 

(ivenv) root@atomdev-01:~/grimoirelab# perceval gitee https://gitee.com/willemjiang/gitee-example repository
[2021-12-07 11:31:14,759] - Sir Perceval is on his quest.
[2021-12-07 11:31:15,001] - Error!: 404 Client Error: Not Found for url: https://gitee.com/api/v5/repos/https://gitee.com/willemjiang/gitee-example/repository/issues?state=all&per_page=100&direction=asc&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00
[2021-12-07 11:31:15,001] - Sir Perceval completed his quest.

Any recommendation for this issue?

**Comment by eyehwan** [comment]
owners and repo information you filled is wrong. 

https://gitee.com/api/v5/repos/willemjiang/gitee-example/issues?state=all&sort=updated&direction=asc&page=1&per_page=20

**Comment by bluejeams** [comment]
I got it, the correct syntax is : perceval gitee willemjiang gitee-example

**Comment by eyehwan** [comment]
Exactly! 
Let's me know if you needed more support on this issue, otherwise I will close it or you can do it by yourself.

**Comment by bluejeams** [comment]
Thanks for your kindly support. This issue can be closed.
