### ISSUE TITLE
Setup wiki page for how to configure openSearch Cluster.

### ISSUE THREAD

**Issue by eyehwan** [grimoirelab-gitee/grimoirelab-perceval-gitee#2]
https://github.com/grimoirelab-gitee/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F

**Comment by shanchenqi** [comment]
Done. Please see details at https://github.com/grimoirelab-gitee/grimoirelab/wiki/How-to-configure-openSearch-cluster%3F.
